# Generated by Django 5.2 on 2025-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRodrigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
