# Generated by Django 5.2 on 2025-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRodrigo', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
